apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: base
  namespace: default
spec:
  interval: 5m
  url: https://github.com/k-guo/veco-basecfg.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kg-veco-site2
  namespace: default
spec:
  interval: 5m
  # targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: base
  path: "./kustomize"
  prune: true
  timeout: 1m
  patches:
    - target:
        kind: VirtualMachine
        name: linux-vm
      patch: |-
        $patch: delete
        apiVersion: v1
        kind: VirtualMachine
        metadata:
          name: linux-vm
